//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace TCG.Sheif.TCG.CategorieService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CategorieServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBase))]
    public partial class CategorieService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private TCGSoapHeader tCGSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetAllCategorieEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDefaultCategoriesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CategorieService() {
            this.Url = global::TCG.Sheif.Properties.Settings.Default.TCG_Sheif_TCG_CategorieService_CategorieService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public TCGSoapHeader TCGSoapHeaderValue {
            get {
                return this.tCGSoapHeaderValueField;
            }
            set {
                this.tCGSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllCategorieEntityCompletedEventHandler GetAllCategorieEntityCompleted;
        
        /// <remarks/>
        public event GetDefaultCategoriesCompletedEventHandler GetDefaultCategoriesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TCGSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCategorieEntity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Categories[] GetAllCategorieEntity() {
            object[] results = this.Invoke("GetAllCategorieEntity", new object[0]);
            return ((Categories[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCategorieEntityAsync() {
            this.GetAllCategorieEntityAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCategorieEntityAsync(object userState) {
            if ((this.GetAllCategorieEntityOperationCompleted == null)) {
                this.GetAllCategorieEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCategorieEntityOperationCompleted);
            }
            this.InvokeAsync("GetAllCategorieEntity", new object[0], this.GetAllCategorieEntityOperationCompleted, userState);
        }
        
        private void OnGetAllCategorieEntityOperationCompleted(object arg) {
            if ((this.GetAllCategorieEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCategorieEntityCompleted(this, new GetAllCategorieEntityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TCGSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDefaultCategories", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Categories[] GetDefaultCategories() {
            object[] results = this.Invoke("GetDefaultCategories", new object[0]);
            return ((Categories[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDefaultCategoriesAsync() {
            this.GetDefaultCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void GetDefaultCategoriesAsync(object userState) {
            if ((this.GetDefaultCategoriesOperationCompleted == null)) {
                this.GetDefaultCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDefaultCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetDefaultCategories", new object[0], this.GetDefaultCategoriesOperationCompleted, userState);
        }
        
        private void OnGetDefaultCategoriesOperationCompleted(object arg) {
            if ((this.GetDefaultCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDefaultCategoriesCompleted(this, new GetDefaultCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class TCGSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Template))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Categories))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityBase {
        
        private string idField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Template : EntityBase {
        
        private string contentField;
        
        private string skinIdField;
        
        private TemplateType templateTypeField;
        
        private string iParentIdField;
        
        private int iSystemTypeField;
        
        private System.DateTime dUpdateDateField;
        
        private System.DateTime dAddDateField;
        
        private string vcTempNameField;
        
        private string vcUrlField;
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string SkinId {
            get {
                return this.skinIdField;
            }
            set {
                this.skinIdField = value;
            }
        }
        
        /// <remarks/>
        public TemplateType TemplateType {
            get {
                return this.templateTypeField;
            }
            set {
                this.templateTypeField = value;
            }
        }
        
        /// <remarks/>
        public string iParentId {
            get {
                return this.iParentIdField;
            }
            set {
                this.iParentIdField = value;
            }
        }
        
        /// <remarks/>
        public int iSystemType {
            get {
                return this.iSystemTypeField;
            }
            set {
                this.iSystemTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dUpdateDate {
            get {
                return this.dUpdateDateField;
            }
            set {
                this.dUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dAddDate {
            get {
                return this.dAddDateField;
            }
            set {
                this.dAddDateField = value;
            }
        }
        
        /// <remarks/>
        public string vcTempName {
            get {
                return this.vcTempNameField;
            }
            set {
                this.vcTempNameField = value;
            }
        }
        
        /// <remarks/>
        public string vcUrl {
            get {
                return this.vcUrlField;
            }
            set {
                this.vcUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TemplateType {
        
        /// <remarks/>
        SinglePageType,
        
        /// <remarks/>
        InfoType,
        
        /// <remarks/>
        ListType,
        
        /// <remarks/>
        OriginalType,
        
        /// <remarks/>
        SystemPage,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Categories : EntityBase {
        
        private string parentField;
        
        private Template resourceTemplateField;
        
        private Template resourceListTemplateField;
        
        private int iOrderField;
        
        private System.DateTime dUpdateDateField;
        
        private string vcClassNameField;
        
        private string vcNameField;
        
        private string vcDirectoryField;
        
        private string vcUrlField;
        
        private string cVisibleField;
        
        private string dataBaseServiceField;
        
        private string skinIdField;
        
        /// <remarks/>
        public string Parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        public Template ResourceTemplate {
            get {
                return this.resourceTemplateField;
            }
            set {
                this.resourceTemplateField = value;
            }
        }
        
        /// <remarks/>
        public Template ResourceListTemplate {
            get {
                return this.resourceListTemplateField;
            }
            set {
                this.resourceListTemplateField = value;
            }
        }
        
        /// <remarks/>
        public int iOrder {
            get {
                return this.iOrderField;
            }
            set {
                this.iOrderField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dUpdateDate {
            get {
                return this.dUpdateDateField;
            }
            set {
                this.dUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        public string vcClassName {
            get {
                return this.vcClassNameField;
            }
            set {
                this.vcClassNameField = value;
            }
        }
        
        /// <remarks/>
        public string vcName {
            get {
                return this.vcNameField;
            }
            set {
                this.vcNameField = value;
            }
        }
        
        /// <remarks/>
        public string vcDirectory {
            get {
                return this.vcDirectoryField;
            }
            set {
                this.vcDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string vcUrl {
            get {
                return this.vcUrlField;
            }
            set {
                this.vcUrlField = value;
            }
        }
        
        /// <remarks/>
        public string cVisible {
            get {
                return this.cVisibleField;
            }
            set {
                this.cVisibleField = value;
            }
        }
        
        /// <remarks/>
        public string DataBaseService {
            get {
                return this.dataBaseServiceField;
            }
            set {
                this.dataBaseServiceField = value;
            }
        }
        
        /// <remarks/>
        public string SkinId {
            get {
                return this.skinIdField;
            }
            set {
                this.skinIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllCategorieEntityCompletedEventHandler(object sender, GetAllCategorieEntityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCategorieEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCategorieEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Categories[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Categories[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDefaultCategoriesCompletedEventHandler(object sender, GetDefaultCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDefaultCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDefaultCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Categories[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Categories[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591