//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace TCG.Sheif.TCG.SheifConfig {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SheifConfigSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBase))]
    public partial class SheifConfig : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private TCGSoapHeader tCGSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback CreateSheifCategorieConfigOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSheifCategorieConfigOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSheifCategorieConfigByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSheifCategorieConfigsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SheifConfig() {
            this.Url = global::TCG.Sheif.Properties.Settings.Default.TCG_Sheif_TCG_SheifConfig_SheifConfig;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public TCGSoapHeader TCGSoapHeaderValue {
            get {
                return this.tCGSoapHeaderValueField;
            }
            set {
                this.tCGSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateSheifCategorieConfigCompletedEventHandler CreateSheifCategorieConfigCompleted;
        
        /// <remarks/>
        public event UpdateSheifCategorieConfigCompletedEventHandler UpdateSheifCategorieConfigCompleted;
        
        /// <remarks/>
        public event GetSheifCategorieConfigByIdCompletedEventHandler GetSheifCategorieConfigByIdCompleted;
        
        /// <remarks/>
        public event GetSheifCategorieConfigsCompletedEventHandler GetSheifCategorieConfigsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TCGSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateSheifCategorieConfig", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateSheifCategorieConfig(SheifCategorieConfig sheifcategorieconfig) {
            object[] results = this.Invoke("CreateSheifCategorieConfig", new object[] {
                        sheifcategorieconfig});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateSheifCategorieConfigAsync(SheifCategorieConfig sheifcategorieconfig) {
            this.CreateSheifCategorieConfigAsync(sheifcategorieconfig, null);
        }
        
        /// <remarks/>
        public void CreateSheifCategorieConfigAsync(SheifCategorieConfig sheifcategorieconfig, object userState) {
            if ((this.CreateSheifCategorieConfigOperationCompleted == null)) {
                this.CreateSheifCategorieConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSheifCategorieConfigOperationCompleted);
            }
            this.InvokeAsync("CreateSheifCategorieConfig", new object[] {
                        sheifcategorieconfig}, this.CreateSheifCategorieConfigOperationCompleted, userState);
        }
        
        private void OnCreateSheifCategorieConfigOperationCompleted(object arg) {
            if ((this.CreateSheifCategorieConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSheifCategorieConfigCompleted(this, new CreateSheifCategorieConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TCGSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSheifCategorieConfig", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateSheifCategorieConfig(SheifCategorieConfig sheifcategorieconfig) {
            object[] results = this.Invoke("UpdateSheifCategorieConfig", new object[] {
                        sheifcategorieconfig});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSheifCategorieConfigAsync(SheifCategorieConfig sheifcategorieconfig) {
            this.UpdateSheifCategorieConfigAsync(sheifcategorieconfig, null);
        }
        
        /// <remarks/>
        public void UpdateSheifCategorieConfigAsync(SheifCategorieConfig sheifcategorieconfig, object userState) {
            if ((this.UpdateSheifCategorieConfigOperationCompleted == null)) {
                this.UpdateSheifCategorieConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSheifCategorieConfigOperationCompleted);
            }
            this.InvokeAsync("UpdateSheifCategorieConfig", new object[] {
                        sheifcategorieconfig}, this.UpdateSheifCategorieConfigOperationCompleted, userState);
        }
        
        private void OnUpdateSheifCategorieConfigOperationCompleted(object arg) {
            if ((this.UpdateSheifCategorieConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSheifCategorieConfigCompleted(this, new UpdateSheifCategorieConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TCGSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSheifCategorieConfigById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SheifCategorieConfig GetSheifCategorieConfigById(string sheifcategorieconfigid) {
            object[] results = this.Invoke("GetSheifCategorieConfigById", new object[] {
                        sheifcategorieconfigid});
            return ((SheifCategorieConfig)(results[0]));
        }
        
        /// <remarks/>
        public void GetSheifCategorieConfigByIdAsync(string sheifcategorieconfigid) {
            this.GetSheifCategorieConfigByIdAsync(sheifcategorieconfigid, null);
        }
        
        /// <remarks/>
        public void GetSheifCategorieConfigByIdAsync(string sheifcategorieconfigid, object userState) {
            if ((this.GetSheifCategorieConfigByIdOperationCompleted == null)) {
                this.GetSheifCategorieConfigByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSheifCategorieConfigByIdOperationCompleted);
            }
            this.InvokeAsync("GetSheifCategorieConfigById", new object[] {
                        sheifcategorieconfigid}, this.GetSheifCategorieConfigByIdOperationCompleted, userState);
        }
        
        private void OnGetSheifCategorieConfigByIdOperationCompleted(object arg) {
            if ((this.GetSheifCategorieConfigByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSheifCategorieConfigByIdCompleted(this, new GetSheifCategorieConfigByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TCGSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSheifCategorieConfigs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SheifCategorieConfig[] GetSheifCategorieConfigs() {
            object[] results = this.Invoke("GetSheifCategorieConfigs", new object[0]);
            return ((SheifCategorieConfig[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSheifCategorieConfigsAsync() {
            this.GetSheifCategorieConfigsAsync(null);
        }
        
        /// <remarks/>
        public void GetSheifCategorieConfigsAsync(object userState) {
            if ((this.GetSheifCategorieConfigsOperationCompleted == null)) {
                this.GetSheifCategorieConfigsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSheifCategorieConfigsOperationCompleted);
            }
            this.InvokeAsync("GetSheifCategorieConfigs", new object[0], this.GetSheifCategorieConfigsOperationCompleted, userState);
        }
        
        private void OnGetSheifCategorieConfigsOperationCompleted(object arg) {
            if ((this.GetSheifCategorieConfigsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSheifCategorieConfigsCompleted(this, new GetSheifCategorieConfigsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class TCGSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SheifCategorieConfig))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityBase {
        
        private string idField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SheifCategorieConfig : EntityBase {
        
        private string sheifSourceIdField;
        
        private string localCategorieIdField;
        
        private System.DateTime resourceCreateDateTimeField;
        
        /// <remarks/>
        public string SheifSourceId {
            get {
                return this.sheifSourceIdField;
            }
            set {
                this.sheifSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public string LocalCategorieId {
            get {
                return this.localCategorieIdField;
            }
            set {
                this.localCategorieIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ResourceCreateDateTime {
            get {
                return this.resourceCreateDateTimeField;
            }
            set {
                this.resourceCreateDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateSheifCategorieConfigCompletedEventHandler(object sender, CreateSheifCategorieConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateSheifCategorieConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateSheifCategorieConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateSheifCategorieConfigCompletedEventHandler(object sender, UpdateSheifCategorieConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSheifCategorieConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSheifCategorieConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSheifCategorieConfigByIdCompletedEventHandler(object sender, GetSheifCategorieConfigByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSheifCategorieConfigByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSheifCategorieConfigByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SheifCategorieConfig Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SheifCategorieConfig)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSheifCategorieConfigsCompletedEventHandler(object sender, GetSheifCategorieConfigsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSheifCategorieConfigsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSheifCategorieConfigsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SheifCategorieConfig[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SheifCategorieConfig[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591